## Data Cleaning Pipeline using Python

In [72]:
import pandas as pd
import numpy as np

In [73]:
df = pd.read_csv("raw_business_dataset.csv")
df.head()

,Customer ID,Customer Name,Country,Order Date,Product Category,Quantity,Unit Price,Discount,Sales Rep,Rating,Notes,Joined Span
0,C001,Rahim Uddin,Bangladesh,15-01-2024,Electronics,2.0,1200.5,5,Nabil,4.5*,priority client,2019-2024
1,C002,Karim Hasan,bangladesh,15-02-2024,Furniture,NaN,850,NaN,Mitu,4.0*,NaN,2020-2024
2,C003,Anika Sultana,India,12-03-2024,Electronics,3.0,NaN,10,Nabil,3.8*,follow up,2018-2023
3,C004,John Doe,USA,07-03-2024,Office Supplies,1.0,45.99,0,Sam,5.0*,NaN,2017-2021
4,C005,Fatema Noor,NaN,01-04-2024,Electronics,4.0,399.99,7.5,Mitu,4.2*,NaN,2021-2024

In [74]:
df.shape

(17, 12)

In [75]:
df.columns

Index(['Customer ID', 'Customer Name', 'Country', 'Order Date',
       'Product Category', 'Quantity', 'Unit Price', 'Discount', 'Sales Rep',
       'Rating', 'Notes', 'Joined Span'],
      dtype='object')

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       17 non-null     object
 1   Customer Name     17 non-null     object
 2   Country           16 non-null     object
 3   Order Date        17 non-null     object
 4   Product Category  17 non-null     object
 5   Quantity          14 non-null     float64
 6   Unit Price        16 non-null     object
 7   Discount          14 non-null     object
 8   Sales Rep         17 non-null     object
 9   Rating            17 non-null     object
 10  Notes             7 non-null      object
 11  Joined Span       17 non-null     object
dtypes: float64(1), object(11)
memory usage: 1.7+ KB

In [77]:
df.isnull().sum()

Customer ID          0
Customer Name        0
Country              1
Order Date           0
Product Category     0
Quantity             3
Unit Price           1
Discount             3
Sales Rep            0
Rating               0
Notes               10
Joined Span          0
dtype: int64

* convert standerd column name

In [78]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['customer_id', 'customer_name', 'country', 'order_date',
       'product_category', 'quantity', 'unit_price', 'discount', 'sales_rep',
       'rating', 'notes', 'joined_span'],
      dtype='object')

* categorical column missing value fill

In [79]:
df["country"] = df["country"].fillna("Unknown")
df["notes"] = df["notes"].fillna("No Notes")

* numeric column missing value handle

In [80]:
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["quantity"] = df["quantity"].fillna(df["quantity"].median())

In [81]:
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")
df["unit_price"] = df["unit_price"].fillna(df["unit_price"].median())

* drop dupplicate values

In [82]:
df.duplicated().sum()

2

In [83]:
df = df.drop_duplicates()

* Clean Text Columns

In [84]:
df["customer_name"] = df["customer_name"].str.strip().str.title()
df["country"] = df["country"].str.strip().str.title()
df["product_category"] = df["product_category"].str.strip().str.title()
df["sales_rep"] = df["sales_rep"].str.strip().str.title()

* Convert Date Column

In [92]:
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)

* extra 2 column add

In [93]:
df[["rookie_year", "final_year"]] = df["joined_span"].str.split("-", expand=True)

In [97]:
df["rookie_year"] = pd.to_numeric(df["rookie_year"], errors="coerce")
df["final_year"] = pd.to_numeric(df["final_year"], errors="coerce")

* drop columns

In [98]:
df = df.drop(columns=["joined_span"])

* negative value drop

In [99]:
df = df[df["quantity"] >= 0]

* ratting column handling

In [101]:
df["rating"] = df["rating"].str.replace("*", "", regex=False)
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

In [103]:
df["rating"] = df["rating"].fillna(df["rating"].median())

* career length

In [105]:
df["career_length"] = df["final_year"] - df["rookie_year"]

In [106]:
df.head()

,customer_id,customer_name,country,order_date,product_category,quantity,unit_price,discount,sales_rep,rating,notes,rookie_year,final_year,career_length
0,C001,Rahim Uddin,Bangladesh,2024-01-15,Electronics,2.0,1200.50,5,Nabil,4.5,priority client,2019,2024,5
1,C002,Karim Hasan,Bangladesh,2024-02-15,Furniture,2.0,850.00,NaN,Mitu,4.0,No Notes,2020,2024,4
2,C003,Anika Sultana,India,2024-03-12,Electronics,3.0,650.00,10,Nabil,3.8,follow up,2018,2023,5
3,C004,John Doe,Usa,2024-03-07,Office Supplies,1.0,45.99,0,Sam,5.0,No Notes,2017,2021,4
4,C005,Fatema Noor,Unknown,2024-04-01,Electronics,4.0,399.99,7.5,Mitu,4.2,No Notes,2021,2024,3

* gross sales

In [108]:
df['gross_sales'] = df['quantity'] * df['unit_price']

* discount ammount

In [109]:
df["discount"] = pd.to_numeric(df["discount"], errors="coerce")
df["discount"] = df["discount"].fillna(df["discount"].median())

In [112]:
df["discount_amount"] = df["gross_sales"] * (df["discount"] / 100)

* Net Sales

In [113]:
df["net_sales"] = df["gross_sales"] - df["discount_amount"]

* Order Year

In [114]:
df["order_year"] = df["order_date"].dt.year

## Final check

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       14 non-null     object
 1   customer_name     14 non-null     object
 2   country           14 non-null     object
 3   order_date        14 non-null     datetime64[ns]
 4   product_category  14 non-null     object
 5   quantity          14 non-null     float64
 6   unit_price        14 non-null     float64
 7   discount          14 non-null     float64
 8   sales_rep         14 non-null     object
 9   rating            14 non-null     float64
 10  notes             14 non-null     object
 11  rookie_year       14 non-null     int64
 12  final_year        14 non-null     int64
 13  career_length     14 non-null     int64
 14  gross_sales       14 non-null     float64
 15  discount_amount   14 non-null     float64
 16  net_sales         14 non-null     float64
 17  order_year        14 non-null     int32
dtypes: datetime64[ns](1), float64(7), int32(1), int64(3), object(6)
memory usage: 2.0+ KB

In [117]:
df.head()

,customer_id,customer_name,country,order_date,product_category,quantity,unit_price,discount,sales_rep,rating,notes,rookie_year,final_year,career_length,gross_sales,discount_amount,net_sales,order_year
0,C001,Rahim Uddin,Bangladesh,2024-01-15,Electronics,2.0,1200.50,5.0,Nabil,4.5,priority client,2019,2024,5,2401.00,120.050,2280.950,2024
1,C002,Karim Hasan,Bangladesh,2024-02-15,Furniture,2.0,850.00,5.0,Mitu,4.0,No Notes,2020,2024,4,1700.00,85.000,1615.000,2024
2,C003,Anika Sultana,India,2024-03-12,Electronics,3.0,650.00,10.0,Nabil,3.8,follow up,2018,2023,5,1950.00,195.000,1755.000,2024
3,C004,John Doe,Usa,2024-03-07,Office Supplies,1.0,45.99,0.0,Sam,5.0,No Notes,2017,2021,4,45.99,0.000,45.990,2024
4,C005,Fatema Noor,Unknown,2024-04-01,Electronics,4.0,399.99,7.5,Mitu,4.2,No Notes,2021,2024,3,1599.96,119.997,1479.963,2024

In [118]:
df.isnull().sum()

customer_id         0
customer_name       0
country             0
order_date          0
product_category    0
quantity            0
unit_price          0
discount            0
sales_rep           0
rating              0
notes               0
rookie_year         0
final_year          0
career_length       0
gross_sales         0
discount_amount     0
net_sales           0
order_year          0
dtype: int64